# ---------------------------------------------------------------------------------------
# This file is derived from Tencent HY-Motion 1.0 (https://github.com/Tencent-Hunyuan/HY-Motion-1.0),
# files hymotion/network/{bricks,modulate_layers,encoders,positional_encoding,attention,
# token_refiner,hymotion_mmdit}.py.
# Tencent HY-MOTION 1.0 is licensed under the Tencent HY-MOTION 1.0 Community License Agreement,
# Copyright (c) 2025 Tencent. All Rights Reserved. The trademark rights of "Tencent HY" are owned
# by Tencent or its affiliate.
#
# MODIFIED BY THE TACD AUTHORS (notice required by Section 3(b) of that Agreement):
#   * the seven source files were concatenated into this single module and their
#     package-relative imports removed;
#   * `load_object(...)` string-based construction replaced by direct class construction
#     (SingleTokenRefiner / FinalLayer), and `get_module_device` inlined;
#   * RotaryEmbedding computes its cos/sin table lazily on first use (same CPU float32
#     math as the original) so the module can be built on the `meta` device by
#     transformers' `from_pretrained`;
#   * the `__main__` self-test blocks were removed.
# No numerical behaviour was changed. Generated by tacd_release/tools/vendor_hymotion.py.
# ---------------------------------------------------------------------------------------
import math
from functools import partial
from itertools import repeat
from typing import Any, Callable, Iterable, List, Optional, Tuple, Union

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from einops import rearrange
from torch import Tensor

flash_attn = None
flash_attn_varlen_func = None
_flash_attn_forward = None


def _ntuple(n: int) -> Callable:
    def parse(x: Any) -> Tuple:
        if isinstance(x, Iterable) and not isinstance(x, str):
            x = tuple(x)
            if len(x) == 1:
                x = tuple(repeat(x[0], n))
            return x
        return tuple(repeat(x, n))

    return parse


to_2tuple = _ntuple(2)


def get_module_device(module: nn.Module) -> torch.device:
    return next(module.parameters()).device


# ======== from hymotion/network/bricks.py ========
def get_activation_layer(act_type: str) -> Callable[[], nn.Module]:
    if act_type == "gelu":
        return lambda: nn.GELU()
    elif act_type == "gelu_tanh":
        return lambda: nn.GELU(approximate="tanh")
    elif act_type == "relu":
        return nn.ReLU
    elif act_type == "silu":
        return nn.SiLU
    else:
        raise ValueError(f"Unknown activation type: {act_type}")


def get_norm_layer(norm_type: Optional[str]):
    if norm_type == "layer":
        return nn.LayerNorm
    elif norm_type == "rms":
        return RMSNorm
    elif norm_type == "none" or norm_type is None:
        return nn.Identity
    else:
        raise ValueError(f"Unknown norm type: {norm_type}")


class RMSNorm(nn.Module):
    def __init__(self, dim: int, elementwise_affine=True, eps: float = 1e-6) -> None:
        super().__init__()
        self.eps = eps
        if elementwise_affine:
            self.weight = nn.Parameter(torch.ones(dim))

    def _norm(self, x: Tensor) -> Tensor:
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + self.eps)

    def forward(self, x: Tensor) -> Tensor:
        output = self._norm(x.float()).type_as(x)
        if hasattr(self, "weight"):
            output = output * self.weight
        return output


# ======== from hymotion/network/modulate_layers.py ========
class ModulateDiT(nn.Module):
    def __init__(self, feat_dim: int, factor: int, act_type: str = "silu"):
        super().__init__()
        self.act = get_activation_layer(act_type)()
        self.linear = nn.Linear(feat_dim, factor * feat_dim, bias=True)
        nn.init.zeros_(self.linear.weight)
        nn.init.zeros_(self.linear.bias)

    def forward(self, x: Tensor) -> Tensor:
        return self.linear(self.act(x))


def modulate(x: Tensor, shift: Optional[Tensor] = None, scale: Optional[Tensor] = None) -> Tensor:
    if shift is not None and scale is not None:
        assert len(x.shape) == len(shift.shape) == len(scale.shape), (
            "x, shift, scale must have the same number of dimensions, "
            f"but got x.shape: {x.shape}, "
            f"shift.shape: {shift.shape} "
            f"and scale.shape: {scale.shape}"
        )
    if shift is not None and scale is not None:
        return x * (1 + scale) + shift
    elif shift is not None:
        return x + shift
    elif scale is not None:
        return x * (1 + scale)
    else:
        return x


def apply_gate(x: Tensor, gate: Optional[Tensor] = None, tanh: bool = False) -> Tensor:
    if gate is not None:
        assert len(x.shape) == len(
            gate.shape
        ), f"x, gate must have the same number of dimensions, but got {x.shape} and {gate.shape}"
    if gate is None:
        return x
    if tanh:
        return x * gate.tanh()
    else:
        return x * gate


# ======== from hymotion/network/encoders.py ========
class MLP(nn.Module):
    def __init__(
        self,
        in_dim: int,
        feat_dim: int,
        out_dim: Optional[int] = None,
        act_type: str = "gelu",
        norm_type: Optional[str] = None,
        bias: bool = True,
        drop: float = 0.0,
        use_conv: bool = False,
    ) -> None:
        super().__init__()
        out_dim = out_dim or in_dim
        feat_dim = feat_dim or in_dim
        bias = to_2tuple(bias)
        drop_probs = to_2tuple(drop)
        linear_layer = partial(nn.Conv2d, kernel_size=1) if use_conv else nn.Linear

        self.fc1 = linear_layer(in_dim, feat_dim, bias=bias[0] if isinstance(bias, (list, tuple)) else bias)
        self.act = get_activation_layer(act_type)()
        self.drop1 = nn.Dropout(drop_probs[0] if isinstance(drop_probs, (list, tuple)) else drop_probs)
        self.norm = get_norm_layer(norm_type)(feat_dim) if norm_type else nn.Identity()
        self.fc2 = linear_layer(feat_dim, out_dim, bias=bias[1] if isinstance(bias, (list, tuple)) else bias)
        self.drop2 = nn.Dropout(drop_probs[1])

    def forward(self, x: Tensor) -> Tensor:
        x = self.fc1(x)
        x = self.act(x)
        x = self.drop1(x)
        x = self.norm(x)
        x = self.fc2(x)
        x = self.drop2(x)
        return x


class MLPEncoder(nn.Module):
    def __init__(self, in_dim: int, feat_dim: int, num_layers: int, act_type: str = "silu") -> None:
        super(MLPEncoder, self).__init__()
        self.in_dim = in_dim
        self.feat_dim = feat_dim
        linears = []
        linears.append(nn.Linear(in_features=in_dim, out_features=self.feat_dim))
        for i in range(num_layers - 1):
            linears.append(get_activation_layer(act_type)())
            linears.append(nn.Linear(self.feat_dim, self.feat_dim))
        self.linears = nn.Sequential(*linears)

    def forward(self, x: Tensor) -> Tensor:
        return self.linears(x)


class FinalLayer(nn.Module):
    def __init__(self, feat_dim: int, out_dim: int, act_type: str = "gelu", zero_init=False, **kwargs):
        super().__init__()

        self.norm_final = nn.LayerNorm(feat_dim, elementwise_affine=False, eps=1e-6)
        self.adaLN_modulation = ModulateDiT(feat_dim, factor=2, act_type=act_type)
        self.linear = nn.Linear(feat_dim, out_dim, bias=True)
        if zero_init:
            nn.init.zeros_(self.linear.weight)
            nn.init.zeros_(self.linear.bias)

    def forward(self, x: Tensor, adapter: Tensor) -> Tensor:
        shift, scale = self.adaLN_modulation(adapter).chunk(2, dim=-1)
        x = modulate(self.norm_final(x), shift=shift, scale=scale)
        x = self.linear(x)
        return x


class TimestepEmbeddingEncoder(nn.Module):
    def __init__(
        self,
        embedding_dim: int,
        feat_dim: int,
        act_type: str = "silu",
        time_factor: float = 1.0,
    ) -> None:
        super(TimestepEmbeddingEncoder, self).__init__()

        self.embedding_dim = embedding_dim
        self.feat_dim = feat_dim
        self.time_factor = time_factor
        blocks = [
            nn.Linear(embedding_dim, self.feat_dim),
            get_activation_layer(act_type)(),
            nn.Linear(self.feat_dim, self.feat_dim),
        ]
        self.blocks = nn.Sequential(*blocks)

    def forward(self, t: Tensor) -> Tensor:
        x = self.blocks(self.sinusodial_embedding(t, self.embedding_dim, time_factor=self.time_factor)).unsqueeze(1)
        return x

    @staticmethod
    def sinusodial_embedding(
        timesteps: Tensor, embedding_dim: int, temperature: float = 10000.0, time_factor: float = 1.0
    ) -> Tensor:
        assert len(timesteps.shape) == 1, "Timesteps should be a 1d-array"
        timesteps = timesteps * time_factor
        half = embedding_dim // 2
        freqs = torch.exp(
            -torch.log(torch.tensor(temperature)) * torch.arange(start=0, end=half, dtype=torch.float) / half
        ).to(device=timesteps.device)
        args = timesteps[:, None].float() * freqs[None]
        embedding = torch.cat([torch.cos(args), torch.sin(args)], dim=-1)
        if embedding_dim % 2:
            embedding = torch.cat([embedding, torch.zeros_like(embedding[:, :1])], dim=-1)
        return embedding


# ======== from hymotion/network/positional_encoding.py ========
class RotaryEmbedding(nn.Module):
    def __init__(
        self,
        num_feats: int,
        max_seq_len: Union[Tensor, int],
        temperature: int = 10000,
        use_real: bool = False,
        theta_rescale_factor: float = 1.0,
        interpolation_factor: float = 1.0,
    ) -> None:
        super(RotaryEmbedding, self).__init__()
        assert num_feats % 2 == 0, "num_feats (head_dim) must be even for RoPE."
        self.num_feats = num_feats
        self.max_seq_len = max_seq_len
        self.temperature = temperature
        self.use_real = use_real
        self.theta_rescale_factor = theta_rescale_factor
        self.interpolation_factor = interpolation_factor

        self._freqs_cis = None

    @property
    def freqs_cis(self):
        if self._freqs_cis is None:
            self._freqs_cis = self._build_freqs_cis()
        return self._freqs_cis

    def _build_freqs_cis(self):
        # TACD modification: formerly executed in __init__; always built on CPU in float32.
        max_seq_len, temperature = self.max_seq_len, self.temperature
        theta_rescale_factor, interpolation_factor = self.theta_rescale_factor, self.interpolation_factor
        use_real = self.use_real
        with torch.device("cpu"):
            if isinstance(max_seq_len, int):
                max_seq_len = torch.arange(max_seq_len).float()
            return self._build_freqs_cis_inner(max_seq_len, temperature, theta_rescale_factor,
                                               interpolation_factor, use_real)

    def _build_freqs_cis_inner(self, max_seq_len, temperature, theta_rescale_factor,
                               interpolation_factor, use_real):
        if theta_rescale_factor != 1.0:
            temperature *= theta_rescale_factor ** (self.num_feats / (self.num_feats - 2))
        dim_t = torch.arange(0, self.num_feats, 2, dtype=torch.float32)
        freqs = 1.0 / (temperature ** (2 * torch.div(dim_t, 2, rounding_mode="trunc") / self.num_feats))  # [D/2]
        freqs = torch.outer(max_seq_len.float() * interpolation_factor, freqs)  # [S, D/2]
        if use_real:
            freqs_cos = freqs.cos().repeat_interleave(2, dim=1)  # [S, D]
            freqs_sin = freqs.sin().repeat_interleave(2, dim=1)  # [S, D]
            return (freqs_cos, freqs_sin)
        else:
            freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # [S, D/2]
            return freqs_cis

    def reshape_for_broadcast(
        self, freqs_cis: Union[Tensor, Tuple[Tensor, Tensor]], x: Tensor
    ) -> Union[Tuple[Tensor, Tensor], Tensor]:
        ndim = x.ndim
        assert 0 <= 1 < ndim

        if isinstance(freqs_cis, tuple):
            # freqs_cis: (cos, sin) in real space
            assert (
                freqs_cis[0].shape[-1] == x.shape[-1]
            ), f"freqs_cis shape {freqs_cis[0].shape} does not match x shape {x.shape} on the head_dim dimension"
            assert freqs_cis[0].shape[0] >= x.shape[1], (
                f"freqs_cis shape {freqs_cis[0].shape} should be larger than or equal to "
                f"x shape {x.shape} on the time dimension"
            )
            shape = []
            for i, d in enumerate(x.shape):
                if i == 1:
                    shape.append(-1)
                elif i == ndim - 1:
                    shape.append(d)
                else:
                    shape.append(1)
            return (
                freqs_cis[0].view(*shape)[:, : x.shape[1], ...],
                freqs_cis[1].view(*shape)[:, : x.shape[1], ...],
            )
        else:
            # freqs_cis: values in complex space
            assert (
                freqs_cis.shape[-1] == x.shape[-1]
            ), f"freqs_cis shape {freqs_cis.shape} does not match x shape {x.shape} on the head_dim dimension"
            assert freqs_cis.shape[0] >= x.shape[1], (
                f"freqs_cis shape {freqs_cis.shape} should be larger than or equal to "
                f"x shape {x.shape} on the time dimension"
            )
            shape = []
            for i, d in enumerate(x.shape):
                if i == 1:
                    shape.append(-1)
                elif i == ndim - 1:
                    shape.append(d)
                else:
                    shape.append(1)
            return freqs_cis.view(*shape)[:, : x.shape[1], ...]

    def rotate_half(self, x: Tensor) -> Tensor:
        x_real, x_imag = x.float().reshape(*x.shape[:-1], -1, 2).unbind(-1)  # [B, S, H, D//2]
        return torch.stack([-x_imag, x_real], dim=-1).flatten(3)

    def apply_rotary_emb(self, xq: Tensor, xk: Tensor) -> Tuple[Tensor, Tensor]:
        xk_out = None
        if isinstance(self.freqs_cis, tuple):
            cos, sin = self.reshape_for_broadcast(self.freqs_cis, xq)  # [B, L, H, D]
            cos, sin = cos.to(xq.device), sin.to(xq.device)
            # real * cos - imag * sin
            # imag * cos + real * sin
            xq_out = (xq.float() * cos + self.rotate_half(xq.float()) * sin).type_as(xq)
            xk_out = (xk.float() * cos + self.rotate_half(xk.float()) * sin).type_as(xk)
        else:
            # view_as_complex will pack [..., D/2, 2](real) to [..., D/2](complex)
            xq_ = torch.view_as_complex(xq.float().reshape(*xq.shape[:-1], -1, 2))  # [B, S, H, D//2]
            freqs_cis = self.reshape_for_broadcast(self.freqs_cis, xq_)
            # Handle device transfer based on return type
            if isinstance(freqs_cis, tuple):
                freqs_cis = (freqs_cis[0].to(xq.device), freqs_cis[1].to(xq.device))
            else:
                freqs_cis = freqs_cis.to(xq.device)  # [S, D//2] --> [1, S, 1, D//2]
            # (real, imag) * (cos, sin) = (real * cos - imag * sin, imag * cos + real * sin)
            # view_as_real will expand [..., D/2](complex) to [..., D/2, 2](real)
            xq_out = torch.view_as_real(xq_ * freqs_cis).flatten(3).type_as(xq)
            xk_ = torch.view_as_complex(xk.float().reshape(*xk.shape[:-1], -1, 2))  # [B, S, H, D//2]
            xk_out = torch.view_as_real(xk_ * freqs_cis).flatten(3).type_as(xk)

        return xq_out, xk_out

    def __repr__(self) -> str:
        repr_str = self.__class__.__name__
        repr_str += f"(num_feats={self.num_feats}, "
        repr_str += f"max_seq_len={self.max_seq_len}, "
        repr_str += f"temperature={self.temperature}, "
        repr_str += f"use_real={self.use_real}, "
        repr_str += f"theta_rescale_factor={self.theta_rescale_factor}, "
        repr_str += f"interpolation_factor={self.interpolation_factor})"
        return repr_str


class PositionalEncoding(nn.Module):
    def __init__(self, num_feats: int, dropout: float = 0.1, max_len: int = 5000):
        super(PositionalEncoding, self).__init__()
        self.dropout = nn.Dropout(p=dropout)

        pe = torch.zeros(max_len, num_feats)
        position = torch.arange(0, max_len, dtype=torch.float).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, num_feats, 2).float() * (-np.log(10000.0) / num_feats))
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        pe = pe.unsqueeze(0)  # shape of [1, L, D]
        self.register_buffer("pe", pe)

    def forward(self, x: Tensor) -> Tensor:
        x = x + self.pe[:, : x.shape[1], :]  # shape of [B, L, D]
        return self.dropout(x)


# ======== from hymotion/network/attention.py ========
MEMORY_LAYOUT = {
    "flash": (lambda x: x.view(x.shape[0] * x.shape[1], *x.shape[2:]), lambda x: x),
    "torch": (lambda x: x.transpose(1, 2), lambda x: x.transpose(1, 2)),
    "vanilla": (lambda x: x.transpose(1, 2), lambda x: x.transpose(1, 2)),
}


def attention(
    q: Tensor,
    k: Tensor,
    v: Tensor,
    mode: str = "flash",
    drop_rate: float = 0.0,
    attn_mask: Optional[Tensor] = None,
    causal: bool = False,
    cu_seqlens_q: Optional[Tensor] = None,
    cu_seqlens_kv: Optional[Tensor] = None,
    max_seqlen_q: Optional[int] = None,
    max_seqlen_kv: Optional[int] = None,
    batch_size: int = 1,
    training: bool = True,
) -> Union[Tensor, Tuple[Tensor, Tensor]]:
    """Perform QKV self attention.

    Args:
        q (Tensor): Query tensor with shape [b, s, h, d], where h is the number of heads.
        k (Tensor): Key tensor with shape [b, s1, h, d]
        v (Tensor): Value tensor with shape [b, s1, h, d]
        mode (str): Attention mode. Choose from 'self_flash', 'cross_flash', 'torch', and 'vanilla'.
        drop_rate (float): Dropout rate in attention map. (default: 0)
        attn_mask (Tensor): Attention mask with shape [b, s1] (cross_attn), or [b, h, s, s1] (torch or vanilla).
            (default: None)
        causal (bool): Whether to use causal attention. (default: False)
        cu_seqlens_q (Tensor): dtype torch.int32. The cumulative sequence lengths of the sequences in the batch,
            used to index into q.
        cu_seqlens_kv (Tensor): dtype torch.int32. The cumulative sequence lengths of the sequences in the batch,
            used to index into kv.
        max_seqlen_q (int): The maximum sequence length in the batch of q.
        max_seqlen_kv (int): The maximum sequence length in the batch of k and v.

    Returns:
        Tensor: Output tensor after self attention with shape [b, s, hd]
    """
    pre_attn_layout, post_attn_layout = MEMORY_LAYOUT[mode]
    q = pre_attn_layout(q)
    k = pre_attn_layout(k)
    v = pre_attn_layout(v)

    if mode == "torch":
        if attn_mask is not None and attn_mask.dtype != torch.bool:
            attn_mask = attn_mask.to(q.dtype)
        x = F.scaled_dot_product_attention(q, k, v, attn_mask=attn_mask, dropout_p=drop_rate, is_causal=causal)
    elif mode == "flash":
        assert flash_attn_varlen_func is not None, "flash_attn is not installed or not supported"
        x = flash_attn_varlen_func(
            q,
            k,
            v,
            cu_seqlens_q,
            cu_seqlens_kv,
            max_seqlen_q,
            max_seqlen_kv,
        )
        # x with shape [(bxs), a, d]
        x = x.view(batch_size, max_seqlen_q, x.shape[-2], x.shape[-1])  # reshape x to [b, s, a, d]
    elif mode == "vanilla":
        scale_factor = 1.0 / math.sqrt(q.size(-1))
        b, a, s_q, _ = q.shape
        s_k = k.size(2)
        attn_bias = torch.zeros(b, a, s_q, s_k, dtype=q.dtype, device=q.device)
        if causal:
            # Only applied to self attention
            assert attn_mask is None, "Causal mask and attn_mask cannot be used together"
            temp_mask = torch.ones(b, a, s_q, s_q, dtype=torch.bool, device=q.device).tril(diagonal=0)
            attn_bias.masked_fill_(~temp_mask, float("-inf"))
            attn_bias = attn_bias.to(q.dtype)
        if attn_mask is not None:
            if attn_mask.dtype == torch.bool:
                attn_bias.masked_fill_(~attn_mask, float("-inf"))
            else:
                attn_bias = attn_bias + attn_mask

        attn = (q @ k.transpose(-2, -1)) * scale_factor
        attn = attn + attn_bias
        attn = attn.softmax(dim=-1)
        attn = torch.dropout(attn, p=drop_rate, train=training)
        x = attn @ v
    else:
        raise NotImplementedError(f"Unsupported attention mode: {mode}")

    x = post_attn_layout(x)
    b, s, h, d = x.shape
    out = x.reshape(b, s, -1)
    return out


# ======== from hymotion/network/token_refiner.py ========
class IndividualTokenRefinerBlock(nn.Module):
    def __init__(
        self,
        feat_dim: int,
        num_heads: int,
        mlp_ratio: float = 4.0,
        dropout: float = 0.0,
        mlp_act_type: str = "silu",
        qk_norm_type: str = "layer",
        qkv_bias: bool = True,
    ) -> None:
        super().__init__()
        self.feat_dim = feat_dim
        self.num_heads = num_heads
        self.mlp_ratio = mlp_ratio
        self.dropout = dropout
        assert self.feat_dim % num_heads == 0, f"feat_dim {self.feat_dim} must be divisible by num_heads {num_heads}"
        self.head_dim = feat_dim // num_heads

        self.mlp_hidden_dim = int(feat_dim * mlp_ratio)

        self.norm1 = get_norm_layer(norm_type="layer")(self.feat_dim, elementwise_affine=True, eps=1e-6)
        self.self_attn_qkv = nn.Linear(feat_dim, feat_dim * 3, bias=qkv_bias)
        self.self_attn_q_norm = get_norm_layer(qk_norm_type)(self.head_dim, elementwise_affine=True, eps=1e-6)
        self.self_attn_k_norm = get_norm_layer(qk_norm_type)(self.head_dim, elementwise_affine=True, eps=1e-6)
        self.self_attn_proj = nn.Linear(feat_dim, feat_dim, bias=qkv_bias)

        self.norm2 = get_norm_layer(norm_type="layer")(self.feat_dim, elementwise_affine=True, eps=1e-6)

        self.mlp = MLP(
            in_dim=feat_dim,
            feat_dim=self.mlp_hidden_dim,
            act_type=mlp_act_type,
            drop=dropout,
        )

        self.adaLN_modulation = ModulateDiT(
            feat_dim=feat_dim,
            factor=2,
            act_type="silu",
        )

    def forward(self, x: Tensor, c: Tensor, attn_mask: Optional[Tensor] = None) -> Tensor:
        gate_msa, gate_mlp = self.adaLN_modulation(c).chunk(2, dim=-1)
        norm_x = self.norm1(x)
        qkv = self.self_attn_qkv(norm_x)
        q, k, v = rearrange(qkv, "B L (K H D) -> K B L H D", K=3, H=self.num_heads)
        # Apply QK-Norm if needed
        q = self.self_attn_q_norm(q).to(v)
        k = self.self_attn_k_norm(k).to(v)
        # Self-Attention
        attn = attention(q, k, v, mode="torch", attn_mask=attn_mask)
        x = x + apply_gate(self.self_attn_proj(attn), gate_msa)
        # FFN Layer
        x = x + apply_gate(self.mlp(self.norm2(x)), gate_mlp)
        return x


class IndividualTokenRefiner(nn.Module):
    def __init__(
        self,
        feat_dim: int,
        num_heads: int,
        num_layers: int,
        mlp_ratio: float = 4.0,
        dropout: float = 0.0,
        mlp_act_type: str = "silu",
        qk_norm_type: str = "layer",
        qkv_bias: bool = True,
    ) -> None:
        super().__init__()
        self.blocks = nn.ModuleList(
            [
                IndividualTokenRefinerBlock(
                    feat_dim=feat_dim,
                    num_heads=num_heads,
                    mlp_ratio=mlp_ratio,
                    dropout=dropout,
                    mlp_act_type=mlp_act_type,
                    qk_norm_type=qk_norm_type,
                    qkv_bias=qkv_bias,
                )
                for _ in range(num_layers)
            ]
        )

    def forward(self, x: Tensor, c: Tensor, mask: Optional[Tensor] = None) -> Tensor:
        self_attn_mask = None
        if mask is not None:
            batch_size = mask.shape[0]
            seq_len = mask.shape[1]
            mask = mask.to(x.device)
            # batch_size x 1 x seq_len x seq_len
            self_attn_mask_1 = mask.view(batch_size, 1, 1, seq_len).repeat(1, 1, seq_len, 1)
            # batch_size x 1 x seq_len x seq_len
            self_attn_mask_2 = self_attn_mask_1.transpose(2, 3)
            # batch_size x 1 x seq_len x seq_len, 1 for broadcasting of num_heads
            self_attn_mask = (self_attn_mask_1 & self_attn_mask_2).bool()
            # avoids self-attention weight being NaN for padding tokens
            # assume the shape of self_attn_mask is [B, H, Q, K] and this is self-attention (Q==K==L)
            L = self_attn_mask.size(-1)
            diag = torch.eye(L, dtype=torch.bool, device=self_attn_mask.device).view(1, 1, L, L)  # [1,1,L,L]
            # mark which query row is "all False" (no visible key)
            all_false = ~self_attn_mask.any(dim=-1, keepdim=False)  # [B, H, Q]
            # expand to [B, H, Q, K], only for these rows, back to diagonal visible
            all_false = all_false.unsqueeze(-1).expand(-1, -1, -1, L)
            self_attn_mask = torch.where(all_false, diag.expand_as(self_attn_mask), self_attn_mask)

        if self_attn_mask is not None:
            self_attn_mask = torch.where(
                self_attn_mask,
                torch.zeros_like(self_attn_mask, dtype=torch.float),
                torch.full_like(self_attn_mask, float("-inf"), dtype=torch.float),
            )
        for block in self.blocks:
            x = block(x, c, self_attn_mask)
        return x


class SingleTokenRefiner(nn.Module):
    def __init__(
        self,
        input_dim: int,
        feat_dim: int,
        num_heads: int,
        num_layers: int,
        mlp_ratio: float = 4.0,
        dropout: float = 0.0,
        mlp_act_type: str = "silu",
        qk_norm_type: str = "layer",
        qkv_bias: bool = True,
        attn_mode: str = "torch",
        **kwargs,
    ) -> None:
        super().__init__()
        self.attn_mode = attn_mode
        assert self.attn_mode == "torch", "Only support 'torch' mode for token refiner."

        self.input_embedder = nn.Linear(input_dim, feat_dim, bias=True)
        self.context_encoder = MLPEncoder(
            in_dim=feat_dim,
            feat_dim=feat_dim,
            num_layers=2,
            act_type=mlp_act_type,
        )
        self.timestep_encoder = TimestepEmbeddingEncoder(
            embedding_dim=feat_dim,
            feat_dim=feat_dim,
            act_type=mlp_act_type,
        )

        self.individual_token_refiner = IndividualTokenRefiner(
            feat_dim=feat_dim,
            num_heads=num_heads,
            num_layers=num_layers,
            mlp_ratio=mlp_ratio,
            dropout=dropout,
            mlp_act_type=mlp_act_type,
            qk_norm_type=qk_norm_type,
            qkv_bias=qkv_bias,
        )

    def forward(self, x: Tensor, t: Tensor, mask: Optional[Tensor] = None) -> Tensor:
        timestep_aware_representations = self.timestep_encoder(t)

        if mask is None:
            context_aware_representations = x.mean(dim=1)
        else:
            mask_float = mask.float().unsqueeze(-1)
            denom = mask_float.sum(dim=1).clamp_min(1e-6)
            context_aware_representations = (x * mask_float).sum(dim=1) / denom
        context_aware_representations = self.context_encoder(context_aware_representations).unsqueeze(1)
        c = timestep_aware_representations + context_aware_representations

        x = self.input_embedder(x)

        x = self.individual_token_refiner(x, c, mask)

        return x


# ======== from hymotion/network/hymotion_mmdit.py ========
class MMBaseBlock(nn.Module):
    def __init__(
        self,
        feat_dim: int,
        num_heads: int,
        mlp_ratio: float,
        dropout: float,
        positional_encoding_cfg: dict,
        apply_rope_to_single_branch: bool,
    ):
        super().__init__()
        self.feat_dim = feat_dim
        self.num_heads = num_heads
        self.mlp_ratio = mlp_ratio
        self.dropout = dropout

        assert self.feat_dim % num_heads == 0, f"feat_dim {self.feat_dim} must be divisible by num_heads {num_heads}"
        self.head_dim = self.feat_dim // num_heads

        self.mlp_hidden_dim = int(self.feat_dim * mlp_ratio)

        self._positional_encoding_cfg = positional_encoding_cfg.copy()
        self.rotary_emb = RotaryEmbedding(num_feats=self.head_dim, **self._positional_encoding_cfg)
        self.apply_rope_to_single_branch = apply_rope_to_single_branch


class MMDoubleStreamBlock(MMBaseBlock):
    def __init__(
        self,
        feat_dim: int,
        num_heads: int,
        mlp_ratio: float,
        dropout: float,
        mlp_act_type: str,
        qk_norm_type: Optional[str] = None,
        qkv_bias: bool = False,
        positional_encoding_cfg: dict = {
            "max_seq_len": 5000,
            "use_real": True,
        },
        apply_rope_to_single_branch: bool = True,
    ):
        super().__init__(feat_dim, num_heads, mlp_ratio, dropout, positional_encoding_cfg, apply_rope_to_single_branch)

        self.motion_mod = ModulateDiT(
            self.feat_dim,
            factor=6,
            act_type="silu",
        )
        self.motion_norm1 = get_norm_layer(norm_type="layer")(self.feat_dim, elementwise_affine=False, eps=1e-6)

        motion_qkv_out_dim = self.feat_dim * 3
        self.motion_qkv = nn.Linear(self.feat_dim, motion_qkv_out_dim, bias=qkv_bias)

        self.motion_q_norm = get_norm_layer(qk_norm_type)(self.head_dim, elementwise_affine=True, eps=1e-6)
        self.motion_k_norm = get_norm_layer(qk_norm_type)(self.head_dim, elementwise_affine=True, eps=1e-6)
        self.motion_out_proj = nn.Linear(self.feat_dim, self.feat_dim, bias=qkv_bias)
        self.motion_norm2 = get_norm_layer(norm_type="layer")(self.feat_dim, elementwise_affine=False, eps=1e-6)
        self.motion_mlp = MLP(
            self.feat_dim,
            self.mlp_hidden_dim,
            act_type=mlp_act_type,
            bias=True,
        )

        self.text_mod = ModulateDiT(
            self.feat_dim,
            factor=6,
            act_type="silu",
        )
        self.text_norm1 = get_norm_layer(norm_type="layer")(self.feat_dim, elementwise_affine=False, eps=1e-6)

        text_qkv_out_dim = self.feat_dim * 3
        self.text_qkv = nn.Linear(self.feat_dim, text_qkv_out_dim, bias=qkv_bias)

        self.text_q_norm = get_norm_layer(qk_norm_type)(self.head_dim, elementwise_affine=True, eps=1e-6)
        self.text_k_norm = get_norm_layer(qk_norm_type)(self.head_dim, elementwise_affine=True, eps=1e-6)
        self.text_out_proj = nn.Linear(self.feat_dim, self.feat_dim, bias=qkv_bias)
        self.text_norm2 = get_norm_layer(norm_type="layer")(self.feat_dim, elementwise_affine=False, eps=1e-6)
        self.text_mlp = MLP(
            self.feat_dim,
            self.mlp_hidden_dim,
            act_type=mlp_act_type,
            bias=True,
        )

    def forward(
        self,
        motion_feat: Tensor,
        text_feat: Tensor,
        adapter: Tensor,
        attn_mask: Optional[Tensor] = None,
    ) -> Tuple[Tensor, Tensor]:
        (
            motion_shift_msa,
            motion_scale_msa,
            motion_gate_msa,
            motion_shift_mlp,
            motion_scale_mlp,
            motion_gate_mlp,
        ) = self.motion_mod(adapter).chunk(6, dim=-1)
        (
            text_shift_msa,
            text_scale_msa,
            text_gate_msa,
            text_shift_mlp,
            text_scale_mlp,
            text_gate_mlp,
        ) = self.text_mod(
            adapter
        ).chunk(6, dim=-1)

        motion_modulated = self.motion_norm1(motion_feat)
        motion_modulated = modulate(motion_modulated, shift=motion_shift_msa, scale=motion_scale_msa)
        motion_qkv = self.motion_qkv(motion_modulated)

        motion_q, motion_k, motion_v = rearrange(motion_qkv, "B L (K H D) -> K B L H D", K=3, H=self.num_heads)
        motion_q = self.motion_q_norm(motion_q).to(motion_v)
        motion_k = self.motion_k_norm(motion_k).to(motion_v)

        if self.apply_rope_to_single_branch:
            # NOTE: we don't apply RoPE to text_branch_two here
            motion_q, motion_k = self.rotary_emb.apply_rotary_emb(motion_q, motion_k)

        text_modulated = self.text_norm1(text_feat)
        text_modulated = modulate(text_modulated, shift=text_shift_msa, scale=text_scale_msa)
        text_qkv = self.text_qkv(text_modulated)

        text_q, text_k, text_v = rearrange(
            text_qkv,
            "B L (K H D) -> K B L H D",
            K=3,
            H=self.num_heads,
        )
        text_q = self.text_q_norm(text_q).to(text_v)
        text_k = self.text_k_norm(text_k).to(text_v)

        q = torch.cat((motion_q, text_q), dim=1)
        k = torch.cat((motion_k, text_k), dim=1)
        v = torch.cat((motion_v, text_v), dim=1)

        if not self.apply_rope_to_single_branch:
            q, k = self.rotary_emb.apply_rotary_emb(q, k)

        bsz, total_len, _, _ = q.shape
        motion_len = motion_feat.shape[1]
        text_len = text_feat.shape[1]
        dropout_p = 0.0 if not self.training else self.dropout

        attn_output = attention(
            q,
            k,
            v,
            mode="torch",
            drop_rate=dropout_p,
            attn_mask=attn_mask,
            causal=False,
            cu_seqlens_q=None,
            cu_seqlens_kv=None,
            max_seqlen_q=None,
            max_seqlen_kv=None,
            batch_size=bsz,
            training=self.training,
        )

        motion_attn_output, text_attn_output = (
            attn_output[:, :motion_len, ...],
            attn_output[:, motion_len:, ...],
        )

        motion_feat = motion_feat + apply_gate(self.motion_out_proj(motion_attn_output), gate=motion_gate_msa)
        motion_feat = motion_feat + apply_gate(
            self.motion_mlp(
                modulate(
                    self.motion_norm2(motion_feat),
                    shift=motion_shift_mlp,
                    scale=motion_scale_mlp,
                )
            ),
            gate=motion_gate_mlp,
        )

        text_feat = text_feat + apply_gate(self.text_out_proj(text_attn_output), gate=text_gate_msa)
        text_feat = text_feat + apply_gate(
            self.text_mlp(
                modulate(
                    self.text_norm2(text_feat),
                    shift=text_shift_mlp,
                    scale=text_scale_mlp,
                )
            ),
            gate=text_gate_mlp,
        )

        return motion_feat, text_feat


class MMSingleStreamBlock(MMBaseBlock):
    def __init__(
        self,
        feat_dim: int,
        num_heads: int,
        mlp_ratio: float,
        dropout: float,
        mlp_act_type: str,
        qk_norm_type: Optional[str] = None,
        qkv_bias: bool = False,
        positional_encoding_cfg: dict = {
            "max_seq_len": 5000,
            "use_real": True,
        },
        apply_rope_to_single_branch: bool = True,
    ):
        super().__init__(feat_dim, num_heads, mlp_ratio, dropout, positional_encoding_cfg, apply_rope_to_single_branch)

        self.modulation = ModulateDiT(self.feat_dim, factor=3, act_type="silu")
        self.norm = get_norm_layer(norm_type="layer")(self.feat_dim, elementwise_affine=False, eps=1e-6)

        # qkv and mlp_in
        qkv_factor = 3
        self.linear1 = nn.Linear(self.feat_dim, self.feat_dim * qkv_factor + self.mlp_hidden_dim, bias=qkv_bias)
        # proj and mlp_out
        self.linear2 = nn.Linear(self.feat_dim + self.mlp_hidden_dim, self.feat_dim, bias=qkv_bias)

        self.q_norm = get_norm_layer(qk_norm_type)(self.head_dim, elementwise_affine=True, eps=1e-6)
        self.k_norm = get_norm_layer(qk_norm_type)(self.head_dim, elementwise_affine=True, eps=1e-6)

        self.mlp_act = get_activation_layer(mlp_act_type)()

    def forward(
        self,
        x: Tensor,
        split_len: int,
        adapter: Tensor,
        attn_mask: Optional[Tensor] = None,
    ) -> Tensor:
        (
            shift_msa,
            scale_msa,
            gate_msa,
        ) = self.modulation(
            adapter
        ).chunk(3, dim=-1)
        x_modulated = modulate(self.norm(x), shift_msa, scale_msa)

        qkv, mlp_hidden = torch.split(self.linear1(x_modulated), [3 * self.feat_dim, self.mlp_hidden_dim], dim=-1)
        q, k, v = rearrange(qkv, "B L (K H D) -> K B L H D", K=3, H=self.num_heads)

        q = self.q_norm(q).to(v)
        k = self.k_norm(k).to(v)

        q1, q2 = q[:, :split_len, ...], q[:, split_len:, ...]
        k1, k2 = k[:, :split_len, ...], k[:, split_len:, ...]
        # apply rotary position embedding
        if self.apply_rope_to_single_branch:
            q1, k1 = self.rotary_emb.apply_rotary_emb(q1, k1)
        q = torch.cat((q1, q2), dim=1)
        k = torch.cat((k1, k2), dim=1)
        if not self.apply_rope_to_single_branch:
            q, k = self.rotary_emb.apply_rotary_emb(q, k)

        bsz, total_len = x_modulated.shape[:2]
        dropout_p = 0.0 if not self.training else self.dropout

        attn_output = attention(
            q,
            k,
            v,
            mode="torch",
            drop_rate=dropout_p,
            attn_mask=attn_mask,
            causal=False,
            cu_seqlens_q=None,
            cu_seqlens_kv=None,
            max_seqlen_q=None,
            max_seqlen_kv=None,
            batch_size=bsz,
            training=self.training,
        )
        output = self.linear2(torch.cat((attn_output, self.mlp_act(mlp_hidden)), 2))

        return x + apply_gate(output, gate=gate_msa)


class HunyuanMotionMMDiT(nn.Module):
    def __init__(
        self,
        input_dim: int,
        feat_dim: int,
        output_dim: Optional[int] = None,
        ctxt_input_dim: int = 4096,
        vtxt_input_dim: int = 256,
        text_refiner_module: str = "hymotion/network/token_refiner.SingleTokenRefiner",
        text_refiner_cfg: dict = {
            "num_layers": 2,
        },
        num_layers: int = 12,
        num_heads: int = 16,
        mlp_ratio: float = 4.0,
        mlp_act_type: str = "gelu_tanh",
        norm_type: str = "layer",
        qk_norm_type: str = "rms",
        qkv_bias: bool = True,
        dropout: float = 0.0,
        final_layer_module: str = "hymotion/network/encoders.FinalLayer",
        final_layer_cfg: dict = {
            "act_type": "silu",
        },
        mask_mode: Optional[str] = None,
        apply_rope_to_single_branch: bool = True,
        insert_start_token: bool = False,
        with_long_skip_connection: bool = False,
        time_factor: float = 1.0,
        narrowband_length: float = 2.0,
        **kwargs,
    ):
        super().__init__()
        self.motion_input_dim = input_dim
        self.ctxt_input_dim = ctxt_input_dim
        self.vtxt_input_dim = vtxt_input_dim
        self.feat_dim = feat_dim
        self.output_dim = output_dim or input_dim
        self.mask_mode = mask_mode
        self.insert_start_token = insert_start_token
        self.time_factor = time_factor
        self.narrowband_length = narrowband_length * 30.0
        if self.insert_start_token:
            self.start_token = nn.Parameter(torch.randn(1, feat_dim))
        self.with_long_skip_connection = with_long_skip_connection
        if self.with_long_skip_connection:
            self.long_skip_net = FinalLayer(feat_dim=feat_dim, out_dim=feat_dim, act_type="silu")

        self.input_encoder = nn.Linear(in_features=input_dim, out_features=feat_dim)
        self.ctxt_encoder = nn.Linear(in_features=ctxt_input_dim, out_features=feat_dim)
        self.vtxt_encoder = MLPEncoder(in_dim=vtxt_input_dim, feat_dim=feat_dim, num_layers=2, act_type="silu")
        self.timestep_encoder = TimestepEmbeddingEncoder(
            embedding_dim=feat_dim,
            feat_dim=feat_dim,
            time_factor=time_factor,
        )

        if text_refiner_module != "" and text_refiner_module is not None:
            text_refiner_cfg = dict(text_refiner_cfg, input_dim=feat_dim, feat_dim=feat_dim, num_heads=num_heads)
            self._text_refiner_cfg = text_refiner_cfg.copy()
            self.text_refiner = SingleTokenRefiner(**text_refiner_cfg)

        self.num_layers = num_layers
        assert num_layers % 3 == 0, f"num_layers must be divisible by 3, but got {num_layers}"
        self.mm_double_blocks_layers = int(num_layers // 3)
        self.mm_single_blocks_layers = int(num_layers - num_layers // 3)

        self.double_blocks = nn.ModuleList(
            [
                MMDoubleStreamBlock(
                    feat_dim=feat_dim,
                    num_heads=num_heads,
                    mlp_ratio=mlp_ratio,
                    dropout=dropout,
                    mlp_act_type=mlp_act_type,
                    qk_norm_type=qk_norm_type,
                    qkv_bias=qkv_bias,
                    apply_rope_to_single_branch=apply_rope_to_single_branch,
                )
                for _ in range(self.mm_double_blocks_layers)
            ]
        )

        self.single_blocks = nn.ModuleList(
            [
                MMSingleStreamBlock(
                    feat_dim=feat_dim,
                    num_heads=num_heads,
                    mlp_ratio=mlp_ratio,
                    dropout=dropout,
                    mlp_act_type=mlp_act_type,
                    qk_norm_type=qk_norm_type,
                    qkv_bias=qkv_bias,
                    apply_rope_to_single_branch=apply_rope_to_single_branch,
                )
                for _ in range(self.mm_single_blocks_layers)
            ]
        )

        final_layer_cfg = dict(final_layer_cfg, feat_dim=feat_dim, out_dim=self.output_dim)
        self._final_layer_cfg = final_layer_cfg.copy()
        self.final_layer = FinalLayer(**final_layer_cfg)

    def forward(
        self,
        x: Tensor,
        ctxt_input: Tensor,
        vtxt_input: Tensor,
        timesteps: Tensor,
        x_mask_temporal: Tensor,
        ctxt_mask_temporal: Tensor,
        **kwargs,
    ) -> Tensor:
        device = get_module_device(self)

        motion_feat = self.input_encoder(x)
        if self.with_long_skip_connection:
            origin_feat = motion_feat
        if self.insert_start_token:
            # (B, 1, D) + (B, L, D) -> (B, L+1, D)
            start_token = self.start_token[None].repeat(motion_feat.shape[0], 1, 1)
            motion_feat = torch.cat((start_token, motion_feat), dim=1)
            x_mask_temporal = torch.cat(
                [
                    torch.ones_like(x_mask_temporal[:, :1], dtype=torch.bool),
                    x_mask_temporal,
                ],
                dim=1,
            )

        timestep_feat = self.timestep_encoder(timesteps)
        vtxt_feat = self.vtxt_encoder(vtxt_input.float())
        adapter = timestep_feat + vtxt_feat

        motion_key_padding_mask = self._canonical_mask(x_mask_temporal).to(device)
        ctxt_key_padding_mask = self._canonical_mask(ctxt_mask_temporal).to(device)
        seq_key_padding_mask = torch.cat((motion_key_padding_mask, ctxt_key_padding_mask), dim=1)
        if self.mask_mode is None:
            seq_mask = None
        elif self.mask_mode == "causal":
            motion_len = motion_feat.shape[1]
            seq_mask = torch.triu(
                torch.full((motion_len, motion_len), float("-inf"), device=device),
                diagonal=1,
            )
        elif self.mask_mode == "narrowband":
            window = int(round(self.narrowband_length))
            motion_len = motion_feat.shape[1]
            idx = torch.arange(motion_len, device=device)
            dist = (idx[None, :] - idx[:, None]).abs()
            band = dist <= window
            seq_mask = torch.full((motion_len, motion_len), float("-inf"), device=device)
            seq_mask = seq_mask.masked_fill(band, 0.0)
        else:
            raise ValueError(f"Unsupported mask mode: {self.mask_mode}")

        ctxt_feat = self.ctxt_encoder(ctxt_input.float())
        if hasattr(self, "text_refiner"):
            ctxt_feat = self.text_refiner(x=ctxt_feat, t=timesteps, mask=(ctxt_key_padding_mask == 0).to(device))

        # precompute shared attention masks (broadcastable over heads)
        bsz = x.shape[0]
        motion_len = motion_feat.shape[1]
        text_len = ctxt_feat.shape[1]
        total_len = motion_len + text_len
        mask_dtype = motion_feat.dtype
        attn_mask_double = self._build_dmm_attn_mask_shared(
            bsz=bsz,
            motion_len=motion_len,
            text_len=text_len,
            dtype=mask_dtype,
            key_padding_mask=seq_key_padding_mask,
            attn_mask=seq_mask,
            device=device,
        )
        for i_layer, mod in enumerate(self.double_blocks):
            motion_feat, ctxt_feat = mod(
                motion_feat=motion_feat,
                text_feat=ctxt_feat,
                adapter=adapter,
                attn_mask=attn_mask_double,
            )

        # precompute shared attention masks for single stream blocks too
        split_len = motion_feat.shape[1]
        x = torch.cat((motion_feat, ctxt_feat), 1)
        attn_mask_single = self._build_smm_attn_mask_shared(
            bsz=bsz,
            split_len=split_len,
            total_len=total_len,
            dtype=mask_dtype,
            key_padding_mask=seq_key_padding_mask,
            attn_mask=seq_mask,
            device=device,
        )
        for i_layer, mod in enumerate(self.single_blocks):
            x = mod(
                x=x,
                split_len=split_len,
                adapter=adapter,
                attn_mask=attn_mask_single,
            )

        x = x[:, :split_len, ...]
        if self.insert_start_token:
            x = x[:, 1:, ...]

        if self.with_long_skip_connection:
            # long skip only consider timestep_feat
            x = self.long_skip_net(origin_feat, timestep_feat) + x

        predicted_res = self.final_layer(x, adapter)
        return predicted_res

    @staticmethod
    def _canonical_mask(input_mask: Tensor) -> Tensor:
        if input_mask.ndim == 1:
            input_mask = input_mask.unsqueeze(1)
        key_padding_mask = torch.where(
            input_mask,
            torch.zeros_like(input_mask, dtype=torch.float),
            torch.full_like(input_mask, float("-inf"), dtype=torch.float),
        )
        return key_padding_mask

    def _build_dmm_attn_mask_shared(
        self,
        bsz: int,
        motion_len: int,
        text_len: int,
        dtype: torch.dtype,
        key_padding_mask: Optional[Tensor],
        attn_mask: Optional[Tensor],
        device: torch.device,
    ) -> Tensor:
        """
        NOTE:
                motion_k  text_k
        motion_q [M→M]   [M→T]
        text_q   [T→M]   [T→T]
        only [M→M] contains given mask
        """
        total_len = motion_len + text_len
        base = torch.zeros((bsz, 1, total_len, total_len), dtype=dtype, device=device)
        if attn_mask is not None:
            if attn_mask.dim() != 2 or attn_mask.shape != (motion_len, motion_len):
                raise RuntimeError(
                    f"attn_mask should be 2D with shape {(motion_len, motion_len)}, got {attn_mask.shape}"
                )
            base[:, :, :motion_len, :motion_len] += attn_mask.view(1, 1, motion_len, motion_len)
        if key_padding_mask is not None:
            mask_total_len = key_padding_mask.shape[1]
            if mask_total_len == motion_len:
                pad = torch.zeros((bsz, text_len), dtype=key_padding_mask.dtype, device=device)
                key_padding_mask = torch.cat((key_padding_mask, pad), dim=-1)
            base = base + key_padding_mask.view(bsz, 1, 1, total_len)
        # disable T→M
        base[:, :, motion_len:, :motion_len] = float("-inf")
        return base

    def _build_smm_attn_mask_shared(
        self,
        bsz: int,
        split_len: int,
        total_len: int,
        dtype: torch.dtype,
        key_padding_mask: Optional[Tensor],
        attn_mask: Optional[Tensor],
        device: torch.device,
    ) -> Tensor:
        """
        NOTE:
                motion_k  text_k
        motion_q [M→M]   [M→T]
        text_q   [T→M]   [T→T]
        only [M→M] contains given mask
        """
        base = torch.zeros((bsz, 1, total_len, total_len), dtype=dtype, device=device)
        if attn_mask is not None:
            if attn_mask.dim() != 2 or attn_mask.shape != (split_len, split_len):
                raise RuntimeError(f"attn_mask should be 2D with shape {(split_len, split_len)}, got {attn_mask.shape}")
            base[:, :, :split_len, :split_len] += attn_mask.view(1, 1, split_len, split_len)
        if key_padding_mask is not None:
            mask_total_len = key_padding_mask.shape[1]
            if mask_total_len == split_len:
                pad = torch.zeros(
                    (bsz, total_len - split_len),
                    dtype=key_padding_mask.dtype,
                    device=device,
                )
                key_padding_mask = torch.cat((key_padding_mask, pad), dim=-1)
            base = base + key_padding_mask.view(bsz, 1, 1, total_len)
        # disable T→M
        base[:, :, split_len:, :split_len] = float("-inf")
        return base

